### ISSUE TITLE
fork项目的人无法手动触发任务

### ISSUE THREAD

**Issue by wukongdaily** [wukongdaily/RunFilesBuilder#1]
执行后提示：This job was skipped

**Comment by wukongdaily** [comment]
此问题已解决，建议点击【Sync fork】同步代码即可
https://github.com/wukongdaily/RunFilesBuilder/commit/5b419d949075c9bbfa34117b758172c2b68fb947

**Comment by hofai125** [comment]
Sync fork

**Comment by tommyhe1217** [comment]
if: ${{ github.repository == 'wukongdaily/RunFilesBuilder' || github.event_name == 'workflow_dispatch' }}
这个条件好像没有生效，我Fork后还是6小时运行一次，但是运行的工作流不能正常运行，显示“”This job was skipped

**Comment by wukongdaily** [comment]
> if: ${{ github.repository == 'wukongdaily/RunFilesBuilder' || github.event_name == 'workflow_dispatch' }} 这个条件好像没有生效，我Fork后还是6小时运行一次，但是运行的工作流不能正常运行，显示“”This job was skipped

的确。虽然不耗费资源，但是这个记录是去不掉的。如果想完全去掉，就要删掉定时任务。用户手动触发。
所以等一下 我在项目里删掉定时任务吧。各位需要新版本 可以自行手动触发任务。按需使用。

**Comment by tommyhe1217** [comment]
辛苦了，还是建议选择手动触发任务吧，

**Comment by wukongdaily** [comment]
> 辛苦了，还是建议选择手动触发任务吧，
嗯 修改了
https://github.com/wukongdaily/RunFilesBuilder/commit/4154d96a7f4de77f4c83db46fae80a9eff071ce4
